# Generated by Django 4.2.8 on 2023-12-15 00:54

from django.db import migrations, models
import django.db.models.deletion
import redirector.behaviors


class Migration(migrations.Migration):

    dependencies = [
        ("redirector", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DomainRedirect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("referer", models.TextField(blank=True, null=True)),
                (
                    "domain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="redirects",
                        to="redirector.domain",
                    ),
                ),
            ],
            bases=(redirector.behaviors.Timestampable, models.Model),
        ),
    ]
